language: go

go:
  - 1.12.x
  - 1.13.x
  - 1.14.x
  - 1.15.x

git:
  depth: 1

notifications:
  email: true

script:
  - go test -v -race -coverprofile=coverage.txt -covermode=atomic

after_success:
  - bash <(curl -s https://codecov.io/bash)