name: Code Coverage
on:
  push:
    branches:
      - "main"

jobs:
  coverage:
    name: "Coverage"
    runs-on: ubuntu-latest
    steps:
    - name: "Checkout"
      uses: actions/checkout@v3

    - name: Setup Go
      uses: actions/setup-go@v3
      with:
        go-version: 1.18

    - name: "Test"
      run: go test -v -race -coverprofile=coverage.txt -covermode=atomic

    - name: "Upload coverage"
      uses: codecov/codecov-action@v2
      with:
        files: ./coverage.txt
